wlinsk:
  three-part-login:
    providers:
      gitee:
        clientId: xxx
        clientSecret: xxx
        redirectUrl: xxx
        authorizationUrl: https://gitee.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code&scope=user_info
        tokenUrl: https://gitee.com/oauth/token?grant_type=authorization_code&code={code}&client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}
        userInfoUrl: https://gitee.com/api/v5/user?access_token={access_token}
      wechat:
        clientId: 222
        clientSecret: xxx
        redirectUrl: http://localhost:8081/api/wechatLogin
  log:
    path: ./logs/
    name: wlinsk-ai-ap
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: wlinsk-ai-ap
  datasource:
    url: jdbc:mysql://192.168.130.129:3306/wlinsk-ai-aq?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
  redis:
    client-type: lettuce
    timeout: 10000
    lettuce:
      pool:
        max-wait: 10000 #连接池最大阻塞等待时间
        max-active: 500
        min-idle: 1 # 连接池最小空闲链接默认为0
    host: 192.168.130.129
    port: 6379
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
aliyun:
  oss:
    endpoint: xxx
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
ai:
  apiKey: xxx
