wlinsk:
  log:
    path: ./logs/
    name: wlinsk-ai-ap
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: wlinsk-ai-ap
  datasource:
    url: jdbc:mysql://192.168.130.129:3306/wlinsk-ai-aq?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
  redis:
    client-type: lettuce
    timeout: 10000
    lettuce:
      pool:
        max-wait: 10000 #连接池最大阻塞等待时间
        max-active: 500
        min-idle: 1 # 连接池最小空闲链接默认为0
    host: 192.168.130.129
    port: 6379
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
aliyun:
  oss:
    endpoint: xxxx
    accessKeyId: xxxx
    accessKeySecret: xxxx
    bucketName: xxxx
ai:
  apiKey: xxxx